apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: api-service
  name: api-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: api-service
    spec:
      containers:
      - env:
        - name: POSTGRES_URI
          value: postgres://hola:hola@db/bigbrain
        image: bigbrain:latest
        name: api-service
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
